<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>DustInTheWind.$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>DustInTheWind.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
        <Company>Dust in the Wind</Company>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" Version="33.1.0"/>
    </ItemGroup>

</Project>
